environment:
  my_variable:
    secure: RDkCw7VUvmyMe0+RT5NAaQdurj4QDF7NIRPdFeLf5X4Vuu1AzBvb7I8FoouHzTDH

os: WMF 5

skip_commits:
  message: /updated readme.*|update readme.*s/

build: false

test_script:
  - ps: |
      # Install Dependencies
      Get-PackageProvider -Name NuGet -ForceBootstrap | Out-Null
      Install-Module InvokeBuild -Force
      Invoke-Build -Task InstallDependencies

      # Run Pipeline
      Invoke-Build -Task . -UseNextPSGalleryVersion $true

      # Publish Test Results
      $testResultsFile = (Resolve-Path ".\artifacts\TestResults.xml")
      (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", $testResultsFile)

      # Push All Artifacts
      (Get-ChildItem .\artifacts\*.*) | % { Write-Host "Pushing package $_ as Appveyor artifact"; Push-AppveyorArtifact $_ }

deploy_script:
  - ps: |
      # Publish to Gallery
      Invoke-Build -Task Publish