environment:
  my_variable:
    secure: RDkCw7VUvmyMe0+RT5NAaQdurj4QDF7NIRPdFeLf5X4Vuu1AzBvb7I8FoouHzTDH

os: WMF 5

skip_commits:
  message: /updated readme.*|update readme.*s/

build: false

test_script:
  - ps: . .\build.ps1

deploy_script:
  - ps: |
      # Publish to Gallery
      Invoke-Build -Task Publish